spring.application.name=tier1
spring.datasource.url=jdbc:postgresql://localhost:5432/payments
spring.datasource.username=admin
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.datasource.hikari.maximum-pool-size=50